# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Sensor configuration sample.
# Fields: pipelineId, sensorName, rtspUrl

1, Camera, rtsp://127.0.0.1:8555/live/Camera
