# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Redirect safety-core application logs to a dedicated log file.
if $programname == 'pss_daemon' then /var/log/safety-core.log
if $programname == 'nvpss_daemon' then /var/log/safety-core.log
if $programname == 'nvpsd_gateway' then /var/log/safety-core.log
if $programname == 'mdx_client' then /var/log/safety-core.log
if $programname == 'NVPSB_PSS_SOURCE' then /var/log/safety-core.log
if $programname == 'NVPSB_PSS_SINK' then /var/log/safety-core.log
if $programname == 'NVPSB_PSS_DAEMON' then /var/log/safety-core.log
if $programname == 'NVPSB_PSD_CLIENT' then /var/log/safety-core.log
if $programname == 'NVPSB_SDM_CLIENT' then /var/log/safety-core.log

if $programname == 'pss_daemon' then stop
if $programname == 'nvpss_daemon' then stop
if $programname == 'nvpsd_gateway' then stop
if $programname == 'mdx_client' then stop
if $programname == 'NVPSB_PSS_SOURCE' then stop
if $programname == 'NVPSB_PSS_SINK' then stop
if $programname == 'NVPSB_PSS_DAEMON' then stop
if $programname == 'NVPSB_PSD_CLIENT' then stop
if $programname == 'NVPSB_SDM_CLIENT' then stop
