# pipelineId, sensorName, rtspUrl
1, Camera,    rtsp://localhost:8553/RTSPWriter_World_Cameras_Camera_rgb
2, Camera_01, rtsp://localhost:8553/RTSPWriter_World_Cameras_Camera_01_rgb
3, Camera_02, rtsp://localhost:8553/RTSPWriter_World_Cameras_Camera_02_rgb
