# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(SAFETY_CORE_TARGET_ARCH "aarch64" CACHE STRING "Safety-core target architecture")

set(SAFETY_CORE_AARCH64_TOOLCHAIN_PREFIX "aarch64-linux-gnu" CACHE STRING
  "Prefix for the aarch64 GNU cross-compilation toolchain")
set(SAFETY_CORE_AARCH64_SYSROOT "" CACHE PATH
  "Optional sysroot for the aarch64 target")

if(SAFETY_CORE_AARCH64_SYSROOT)
  set(CMAKE_SYSROOT "${SAFETY_CORE_AARCH64_SYSROOT}" CACHE PATH "aarch64 sysroot")
  set(CMAKE_FIND_ROOT_PATH "${SAFETY_CORE_AARCH64_SYSROOT}")
endif()

find_program(SAFETY_CORE_AARCH64_C_COMPILER
  NAMES "${SAFETY_CORE_AARCH64_TOOLCHAIN_PREFIX}-gcc"
)
find_program(SAFETY_CORE_AARCH64_CXX_COMPILER
  NAMES "${SAFETY_CORE_AARCH64_TOOLCHAIN_PREFIX}-g++"
)
find_program(SAFETY_CORE_AARCH64_AR
  NAMES "${SAFETY_CORE_AARCH64_TOOLCHAIN_PREFIX}-ar"
)
find_program(SAFETY_CORE_AARCH64_RANLIB
  NAMES "${SAFETY_CORE_AARCH64_TOOLCHAIN_PREFIX}-ranlib"
)
find_program(SAFETY_CORE_AARCH64_STRIP
  NAMES "${SAFETY_CORE_AARCH64_TOOLCHAIN_PREFIX}-strip"
)

if(NOT SAFETY_CORE_AARCH64_C_COMPILER
    OR NOT SAFETY_CORE_AARCH64_CXX_COMPILER
    OR NOT SAFETY_CORE_AARCH64_AR
    OR NOT SAFETY_CORE_AARCH64_RANLIB)
  message(FATAL_ERROR
    "aarch64 GNU cross toolchain not found. Install gcc-aarch64-linux-gnu, "
    "g++-aarch64-linux-gnu, and binutils-aarch64-linux-gnu, or set "
    "SAFETY_CORE_AARCH64_TOOLCHAIN_PREFIX."
  )
endif()

set(CMAKE_C_COMPILER "${SAFETY_CORE_AARCH64_C_COMPILER}" CACHE FILEPATH "aarch64 C compiler")
set(CMAKE_CXX_COMPILER "${SAFETY_CORE_AARCH64_CXX_COMPILER}" CACHE FILEPATH "aarch64 C++ compiler")
set(CMAKE_AR "${SAFETY_CORE_AARCH64_AR}" CACHE FILEPATH "aarch64 archiver")
set(CMAKE_RANLIB "${SAFETY_CORE_AARCH64_RANLIB}" CACHE FILEPATH "aarch64 ranlib")
if(SAFETY_CORE_AARCH64_STRIP)
  set(CMAKE_STRIP "${SAFETY_CORE_AARCH64_STRIP}" CACHE FILEPATH "aarch64 strip")
endif()

set(CMAKE_CUDA_HOST_COMPILER "${SAFETY_CORE_AARCH64_CXX_COMPILER}" CACHE FILEPATH
  "aarch64 host compiler used by nvcc")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
